### PR TITLE
Enable no_implicit_optional mypy check and fix issue

### PR DESCRIPTION
**Pull request by rnestler**
A small step towards `mypy --strict` mode.
- See  #429

Checklist:

- [x] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.
- [ ] Add or update relevant docs, in the docs folder and in code.
- [x] Add an entry in `CHANGES.rst` summarizing the change and linking to the issue.
- [ ] Add `.. versionchanged::` entries in any relevant code docs.
- [x] Run `pre-commit` hooks and fix any issues.
- [x] Run `pytest` and `tox`, no tests failed.

### CODE REVIEW

**Comment by rnestler** [comment]
@northernSage You did review #391, want to take a look at this as well?

**Comment by rnestler** [comment]
Is there any update / feedback on this PR?

**Comment by rnestler** [comment]
Bump :slightly_smiling_face:

**Review by northernSage — APPROVED** [review]

**Comment by northernSage** [comment]
Thanks a lot 👍🏻

**Pull request merged**
