### PR TITLE
requirements: Add cachelib dependency

### PR DESCRIPTION
**Pull request by ix5**
Since #308 added a hard requirement for `cachelib`, add it to user-facing `setup.py` as well (it was previously only added to dev-dependencies).

I'm not gonna run this whole test suite, sorry. You pushed a broken release 0.11.0, please phixit ;)

To avoid similar issues in the future, it would probably be better to put non-dev requirements into `requirements/prod.in` and generate regular `requirements.txt` from that. Also remove `cachelib` and other non-test deps from `test.in` and instead `-r prod.in`. But that's for you to decide. 

--- 

Checklist:

- [ ] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.
- [ ] Add or update relevant docs, in the docs folder and in code.
- [ ] Add an entry in `CHANGES.rst` summarizing the change and linking to the issue.
- [ ] Add `.. versionchanged::` entries in any relevant code docs.
- [ ] Run `pre-commit` hooks and fix any issues.
- [ ] Run `pytest` and `tox`, no tests failed.

### CODE REVIEW

**Comment by Berserker66** [comment]
Ran into this problem, it broke our automatic build. Fix would be appreciated.

**Comment by ix5** [comment]
> Ran into this problem, it broke our automatic build. Fix would be appreciated.

FWIW, You can add `cachelib` to your own dependencies in the meantime.

**Comment by Berserker66** [comment]
Yeah, someone is working on that in https://github.com/ArchipelagoMW/Archipelago/pull/589

**Comment by Berserker66** [comment]
Opened Issue https://github.com/pallets-eco/flask-caching/issues/353 for it.

**Comment by northernSage** [comment]
Hey all, thanks for letting me know and sorry about the that!

**Pull request merged**
